language: rust
rust:
- stable
- beta
- nightly
branches:
  only:
  - master
  - travis-ci
  - "/^v.*$/"
os:
- linux
matrix:
  allow_failures:
  - rust: beta
  - rust: nightly
before_deploy:
- cd /home/travis/build/trust-dns/axfrnotify; cargo build --release
- cd /home/travis/build/trust-dns; git clone https://github.com/trust-dns/axfrnotify-deb.git
- cd /home/travis/build/trust-dns/axfrnotify-deb; BIN_DIR=../axfrnotify/target/release
  ARCH=amd64 VERSION=$TRAVIS_TAG TAG=$TRAVIS_TAG DIST=trusty make package
before_install:
- gem install package_cloud
deploy:
  provider: packagecloud
  username: lukaspustina
  token:
    secure: gsNK7iVpj8Sb7/jEBNRxmDBnu1u8LmrieOnh4V7nB45ileE5H2RvRKVKqjzzfSlkzBlIdDUPgovHhheMjM6XvnhTX+e6q+wIpc5UOlhXPd3Q01FfHzylXi/fxkURSf/2TH/4vlZpeZD8wYJ/Lm+2U3WvRHrD7D0BY/1CWOezXcQs5Alw6hVcdu2OR3/SV5e5Z6z94ty+TtbaiVA/Fksq5G+f8xg616VfbnWoG4++62Mt2KJljAXLLrvN6kM5jD0zARyCkhagGWYSkoJr0hQI/uxCY+4VnjZ9DorKnrKlPvLEySCcLfOXbKMqDeVH4YN1//hu7SA5QR7U+sC44u57oiZ9KA+ExOFq9LW3I84C7oj5wUCT8y1CcOFdyS1S0wjsrM07V8iQqW/0gt55Z342uj2OATFLYunXv5KtRqh8ukVNJUXWaBqGZmyGmHfAC2D9eZh/sSS7BshlCOqXLcBYWQjBdB9LFBcFE8pHeNjtI3elcqxhAXPX0uliRyq8hqCEtw5oD+K+lWM6pkdk27KA+POz8vG555NiNcnQJ6yGC+STyalORL2aKpDULhKyy/0O0MDl36vsguWVZpcPOSXnf0wISAOpQ68ydCEwkT8JRXcj0erEWzZpx2kZQ/3mfQe2vVbOimfcLbd+1YaSs45mwjsa6/GLVlmdGwW2javXgK0=
  repository: opensource
  dist: ubuntu/trusty
  package_glob: "**/*.deb"
  skip_cleanup: true
  on:
    tags: true
    condition:
    - "$TRAVIS_OS_NAME == linux"
    - "$TRAVIS_RUST_VERSION == stable"
env:
  global:
  - secure: QIuMZyJm4gxKGoXPcd8xb6DWOwHWXOnLRjddM1p/X1byatS2+37qMVJ3c4jsj8vCh2XC+0t1v+Vj61/+VdO4C7M6uPY7fcBMPwNdLzmkrJqyTtDGMSzM18FrJa1iQ3CPyD2JPbb568y3/lmKxmwBxiLBPX4d5GflrJF1leOSqs6Y8LdCYzQe8b+qyTJt5b2cscp6/5td7ObmIaxnbPjtAMdW99t09ljhz4OKtBCsQCM+VeiOT3QiNTO1rsM1yZbC8Qv5B84yhYiCO2QGM56SHBlQb8htpaVePu7RKeYU+SyE+EPR3xjjMcR0mlm6WkAetokNoK55gnb1Cd0KYUrhyAWMvJxvYSkFI5NMGUIgLm+grtKe/oyr5A9cM3SvAxAdKXjjl1CtLEYeoHotgH1pdsdSBtSx7n2W9ozMd2JjVGKu8+DlhW4lY2fgtXiKFqojSy9aislB4UDOE3yA/Audsq8C8pavUNwaS1H4I5bfJ98liv8ibgL5jl25OdbSzqc9crelIA3XWglj8Hc2jHdLx2QpHG4NdR0O/WX7/Ccw7wq1Z+GHCfdz86NUEOypnr+MTxPV7R1tsQBH8DAq7itx24EqNZkDoULmPiflDdc6o48Ns0GKBftdMSZ/YU+RGbVuybHieXGlnr/1gYzUMP30x2QIVvO19sTDv8BhXQOBV9M=
  - secure: UPnfo6hJKDnd+XuqIvCfj374N3PuBxxG3rK5NoEOnzBWcDxrZwkBxVL+IqJtwDl/OCbZlD1eNDHqdPkSgO0ph+6+tpnCe1KMU2vwwQAG9yCmysmomI7cGcCg8oCvrg76ADlE/UVU0HXIWZgCmlt77KK6gVpagfEiOYUm/ScBJPmJUs0JTgG3RjGRaU//FIJGAwJInSIMpoPHC5XfKdgEEj9426XsbWQcoFwk+InRN6qlnr1hORA7KFPhBkjcnRn1ky/IFYXqjgNwZgGfYyK37idESPZVRd+u+Q8CVHSXrKQRwGGsIb+RZsoigt3AcaAR6ttVssGIlsvLS5VUI3mkjLnQodIoY7EXPqpRAfGTL2TprVcler7NeSVv0FxfxDaAeOGwDDjS5pZ/aLLMydY4eAlCVU5CApNjO7cYHBSGIkIw6I4woCeqNhMPd+rZ7i7AOJds4X26MoFPjNQzOmBkNDYV0X6SjCmMVS2ih2KufVv5QhuZxDg5uJPTSQXjGmQ4YTIdJ+i3Rm3mtJQsN/uXKdI/E/h5o93X/CmaQdpGSjNms7O9r3TMshP9b0YwmNJk4P40BgKaTi/AdTqTplu7+gpDLfrKW1w57gCBiQ8IvMd5fajTQDPrQcebqRaa0EMnGmZnyREsxdsZYGfzgWzfeTRSgtcEAtqvu1z88jiR0SE=
